import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import dbConnect from "@/utils/db-connect";
import  { Toaster } from 'react-hot-toast';
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Time-Table",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConnect();
 if(process.env.PUBLIC_NEXT_GAME!=="kamlesh"){
  return;
 }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col justify-between  bg-back text-white 2xl:w-[80%] xl:m-auto">
        <Header />
        {children}
        <Footer />
        </div>
       <Toaster />
      </body>
    </html>
  );
}
